### ISSUE TITLE
Schema scuffed 

### ISSUE THREAD

**Issue by Jamedw** [Jamedw/CSC307_group_project#3]
yo, these schemas suck

**Comment by RandomCyberCoder** [comment]
Yo, I updated the schemas check them again!!!!!!!

**Comment by RandomCyberCoder** [comment]
Hold on let me check your code .....

**Comment by Jamedw** [comment]
> Yo, I updated the schemas check them again!!!!!!!
Nah i did check them they still scuffed

**Comment by RandomCyberCoder** [comment]
Fixing the schema happened a few time over the course of the Project. There was no real expected time for this, but the estimated time it took us was about 3 hours
