### ISSUE TITLE
Frontend css 

### ISSUE THREAD

**Issue by RandomCyberCoder** [Jamedw/CSC307_group_project#4]
Bro this UI is mad wack. Fix your .CSS files ASAP!!!

**Comment by RandomCyberCoder** [comment]
> Bro this UI is mad wack. Fix your .CSS files ASAP!!!

True

**Comment by Jamedw** [comment]
yo, shut up im bout to boot you from the project

**Comment by RandomCyberCoder** [comment]
Womp Womp

**Comment by Jamedw** [comment]
ok, you're done you're getting booted

**Comment by RandomCyberCoder** [comment]
> yo, shut up im bout to boot you from the project

Downvote

**Comment by RandomCyberCoder** [comment]
Expected 1 hour
Actual 4 hours
